name: Upload to Codecov
on:
  workflow_dispatch:
jobs:
  upload-codecov:
    name: Upload to Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with: 
          java-version: 11
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Run Maven Verify
        run: mvn verify
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./target/site/jacoco/jacoco.xml
